// ─────────────────────────────────────────────────────────────────────
// vMix Shortcut Function Reference — SOURCE OF TRUTH
//
// Auto-generated from the official reference, scraped in full:
//   https://www.vmix.com/help28/ShortcutFunctionReference.html
//   Scraped 2026-05-30 · 714 documented functions · 100% coverage.
//
// Numbered / lettered families are condensed into a single templated
// entry: the variable part of the Function name becomes a {placeholder}
// described by `family` (e.g. OverlayInput{ch} covers OverlayInput1..4,
// SetBus{bus}Volume covers A..G). Every other function is listed 1:1.
// `params` lists, in vMix's documented order, the query args the call
// reads besides the family placeholders.
//
// Do not hand-edit — regenerate via .tmp_gen_shortcuts.cjs against a
// fresh scrape when vMix ships a new version.
// ─────────────────────────────────────────────────────────────────────

export type VmixParamId =
  | "input"
  | "value"
  | "duration"
  | "channel"
  | "mix"
  | "selectedIndex"
  | "selectedName";

export type VmixCategory =
  | "General"
  | "Audio"
  | "Transition"
  | "Output"
  | "Title"
  | "Input"
  | "Overlay"
  | "PlayList"
  | "Scripting"
  | "Replay"
  | "NDI"
  | "PTZ"
  | "Preset"
  | "DataSources"
  | "Browser";

/** A condensed placeholder baked into a Function-name template. */
export type VmixFamilyParam =
  | { id: string; kind: "int"; min: number; max: number; label?: string }
  | { id: string; kind: "enum"; values: string[]; label?: string };

export interface VmixShortcut {
  /** Function name. May contain {placeholders} expanded via `family`. */
  fn: string;
  category: VmixCategory;
  description: string;
  /** Query args read besides any family placeholders, in vMix order. */
  params: VmixParamId[];
  /** Present when `fn` is a condensed template. */
  family?: VmixFamilyParam[];
}

export const VMIX_SHORTCUTS: VmixShortcut[] = [

  // ══════════════════════════ General ══════════════════════════
  { fn: "ActivatorRefresh", category: "General", description: "Refresh all activator device lights and controls", params: [] },
  { fn: "CallManagerShowHide", category: "General", description: "", params: [] },
  { fn: "KeyPress", category: "General", description: "Value = Key", params: ["value"] },
  { fn: "SendKeys", category: "General", description: "Send keys to active window Value = Keys", params: ["value"] },
  { fn: "SetDynamicValue{n}", category: "General", description: "Set Dynamic Value to use when specifying Dynamic1 as a shortcut value. Value = Value", params: ["value"], family: [{ id: "n", kind: "int", min: 1, max: 4, label: "Slot #" }] },
  { fn: "Undo", category: "General", description: "Undo closing Input.", params: [] },

  // ══════════════════════════ Audio ══════════════════════════
  { fn: "Audio", category: "Audio", description: "Toggle Audio Mute On/Off", params: ["input"] },
  { fn: "AudioAuto", category: "Audio", description: "", params: ["input"] },
  { fn: "AudioAutoOff", category: "Audio", description: "", params: ["input"] },
  { fn: "AudioAutoOn", category: "Audio", description: "", params: ["input"] },
  { fn: "AudioBus", category: "Audio", description: "M,A,B,C,D,E,F,G Value = Bus", params: ["value", "input"] },
  { fn: "AudioBusOff", category: "Audio", description: "M,A,B,C,D,E,F,G Value = Bus", params: ["value", "input"] },
  { fn: "AudioBusOn", category: "Audio", description: "M,A,B,C,D,E,F,G Value = Bus", params: ["value", "input"] },
  { fn: "AudioChannelMatrixApplyPreset", category: "Audio", description: "Apply preset to channel matrix Value = Preset Name", params: ["value", "input"] },
  { fn: "AudioMixerShowHide", category: "Audio", description: "", params: [] },
  { fn: "AudioOff", category: "Audio", description: "", params: ["input"] },
  { fn: "AudioOn", category: "Audio", description: "", params: ["input"] },
  { fn: "AudioPluginOff", category: "Audio", description: "Turn off Audio Plugin, starting from 1 Value = Plugin Number", params: ["value", "input"] },
  { fn: "AudioPluginOn", category: "Audio", description: "Turn on Audio Plugin, starting from 1 Value = Plugin Number", params: ["value", "input"] },
  { fn: "AudioPluginOnOff", category: "Audio", description: "Toggle on/off Audio Plugin, starting from 1 Value = Plugin Number", params: ["value", "input"] },
  { fn: "AudioPluginShow", category: "Audio", description: "Show Audio Plugin Editor, starting from 1 Value = Plugin Number", params: ["value", "input"] },
  { fn: "BusAAudio", category: "Audio", description: "", params: [] },
  { fn: "BusAAudioOff", category: "Audio", description: "", params: [] },
  { fn: "BusAAudioOn", category: "Audio", description: "", params: [] },
  { fn: "BusAAudioPluginOff", category: "Audio", description: "Turn off Audio Plugin, starting from 1 Value = Plugin Number", params: ["value"] },
  { fn: "BusAAudioPluginOn", category: "Audio", description: "Turn on Audio Plugin, starting from 1 Value = Plugin Number", params: ["value"] },
  { fn: "BusAAudioPluginOnOff", category: "Audio", description: "Toggle on/off Audio Plugin, starting from 1 Value = Plugin Number", params: ["value"] },
  { fn: "BusAAudioPluginShow", category: "Audio", description: "Show Audio Plugin Editor, starting from 1 Value = Plugin Number", params: ["value"] },
  { fn: "BusBAudio", category: "Audio", description: "", params: [] },
  { fn: "BusBAudioOff", category: "Audio", description: "", params: [] },
  { fn: "BusBAudioOn", category: "Audio", description: "", params: [] },
  { fn: "BusBAudioPluginOff", category: "Audio", description: "Turn off Audio Plugin, starting from 1 Value = Plugin Number", params: ["value"] },
  { fn: "BusBAudioPluginOn", category: "Audio", description: "Turn on Audio Plugin, starting from 1 Value = Plugin Number", params: ["value"] },
  { fn: "BusBAudioPluginOnOff", category: "Audio", description: "Toggle on/off Audio Plugin, starting from 1 Value = Plugin Number", params: ["value"] },
  { fn: "BusBAudioPluginShow", category: "Audio", description: "Show Audio Plugin Editor, starting from 1 Value = Plugin Number", params: ["value"] },
  { fn: "BusXAudio", category: "Audio", description: "M,A,B,C,D,E,F,G Value = Bus", params: ["value"] },
  { fn: "BusXAudioOff", category: "Audio", description: "M,A,B,C,D,E,F,G Value = Bus", params: ["value"] },
  { fn: "BusXAudioOn", category: "Audio", description: "M,A,B,C,D,E,F,G Value = Bus", params: ["value"] },
  { fn: "BusXAudioPluginOff", category: "Audio", description: "Turn off Audio Plugin, starting from 1 Value = Bus,PluginNumber", params: ["value"] },
  { fn: "BusXAudioPluginOn", category: "Audio", description: "Turn on Audio Plugin, starting from 1 Value = Bus,PluginNumber", params: ["value"] },
  { fn: "BusXAudioPluginOnOff", category: "Audio", description: "Toggle on/off Audio Plugin, starting from 1 Value = Bus,PluginNumber", params: ["value"] },
  { fn: "BusXAudioPluginShow", category: "Audio", description: "Show Audio Plugin Editor, starting from 1 Value = Bus,PluginNumber", params: ["value"] },
  { fn: "BusXSendToMaster", category: "Audio", description: "M,A,B,C,D,E,F,G Value = Bus", params: ["value"] },
  { fn: "BusXSendToMasterOff", category: "Audio", description: "M,A,B,C,D,E,F,G Value = Bus", params: ["value"] },
  { fn: "BusXSendToMasterOn", category: "Audio", description: "M,A,B,C,D,E,F,G Value = Bus", params: ["value"] },
  { fn: "BusXSolo", category: "Audio", description: "M,A,B,C,D,E,F,G Value = Bus", params: ["value"] },
  { fn: "BusXSoloOff", category: "Audio", description: "M,A,B,C,D,E,F,G Value = Bus", params: ["value"] },
  { fn: "BusXSoloOn", category: "Audio", description: "M,A,B,C,D,E,F,G Value = Bus", params: ["value"] },
  { fn: "MasterAudio", category: "Audio", description: "", params: [] },
  { fn: "MasterAudioOff", category: "Audio", description: "", params: [] },
  { fn: "MasterAudioOn", category: "Audio", description: "", params: [] },
  { fn: "MasterAudioPluginOff", category: "Audio", description: "Turn off Audio Plugin, starting from 1 Value = Plugin Number", params: ["value"] },
  { fn: "MasterAudioPluginOn", category: "Audio", description: "Turn on Audio Plugin, starting from 1 Value = Plugin Number", params: ["value"] },
  { fn: "MasterAudioPluginOnOff", category: "Audio", description: "Toggle on/off Audio Plugin, starting from 1 Value = Plugin Number", params: ["value"] },
  { fn: "MasterAudioPluginShow", category: "Audio", description: "Show Audio Plugin Editor, starting from 1 Value = Plugin Number", params: ["value"] },
  { fn: "SetBalance", category: "Audio", description: "Value = Balance -1-1", params: ["value", "input"] },
  { fn: "SetBus{bus}Volume", category: "Audio", description: "Value = Volume 0-100", params: ["value"], family: [{ id: "bus", kind: "enum", values: ["A", "B", "C", "D", "E", "F", "G"], label: "Bus" }] },
  { fn: "SetBus{bus}VolumeFade", category: "Audio", description: "Set volume gradually over x milliseconds. Value = Volume 0-100,Milliseconds", params: ["value"], family: [{ id: "bus", kind: "enum", values: ["A", "B", "C", "D", "E", "F", "G"], label: "Bus" }] },
  { fn: "SetGain", category: "Audio", description: "Value = Gain dB 0-24", params: ["value", "input"] },
  { fn: "SetGainChannel{ch}", category: "Audio", description: "Value = Gain dB 0-24", params: ["value", "input"], family: [{ id: "ch", kind: "int", min: 1, max: 2, label: "Channel" }] },
  { fn: "SetHeadphonesVolume", category: "Audio", description: "Value = Volume 0-100", params: ["value"] },
  { fn: "SetMasterVolume", category: "Audio", description: "Value = Volume 0-100", params: ["value"] },
  { fn: "SetMasterVolumeFade", category: "Audio", description: "Set volume gradually over x milliseconds. Value = Volume 0-100,Milliseconds", params: ["value"] },
  { fn: "SetVolume", category: "Audio", description: "Value = Volume 0-100", params: ["value", "input"] },
  { fn: "SetVolumeBusMixer", category: "Audio", description: "Set Volume of an Input's Bus Mixer (M,A,B,C,D,E,F,G) Value = Bus,Volume 0-100", params: ["value", "input"] },
  { fn: "SetVolumeBusMixer{bus}", category: "Audio", description: "Set Volume of an Input's A Bus Value = Volume 0-100", params: ["value", "input"], family: [{ id: "bus", kind: "enum", values: ["M", "A", "B", "C", "D", "E", "F", "G"], label: "Bus" }] },
  { fn: "SetVolumeChannel{ch}", category: "Audio", description: "When using SeparateMono on an Audio Input, this can be used to set channel volumes independently. Value = Volume 0-100", params: ["value", "input"], family: [{ id: "ch", kind: "int", min: 1, max: 2, label: "Channel" }] },
  { fn: "SetVolumeChannelMixer", category: "Audio", description: "Set Volume of an Input's sub channel (1 to 16) Value = Channel,Volume 0-100", params: ["value", "input"] },
  { fn: "SetVolumeChannelMixer{n}", category: "Audio", description: "Set Volume of an Input's sub channel 1 Value = Volume 0-100", params: ["value", "input"], family: [{ id: "n", kind: "int", min: 1, max: 16, label: "Sub-channel" }] },
  { fn: "SetVolumeFade", category: "Audio", description: "Set volume gradually over x milliseconds. Value = Volume 0-100,Milliseconds", params: ["value", "input"] },
  { fn: "Solo", category: "Audio", description: "", params: ["input"] },
  { fn: "SoloAllOff", category: "Audio", description: "Turn off Solo for all Inputs and Busses", params: [] },
  { fn: "SoloOff", category: "Audio", description: "", params: ["input"] },
  { fn: "SoloOn", category: "Audio", description: "", params: ["input"] },
  { fn: "SoloPFL", category: "Audio", description: "Toggle between AFL or PFL mode for Solo", params: ["input"] },
  { fn: "SoloPFLOff", category: "Audio", description: "Turn off PFL mode for Solo", params: ["input"] },
  { fn: "SoloPFLOn", category: "Audio", description: "Turn on PFL mode for Solo", params: ["input"] },

  // ══════════════════════════ Transition ══════════════════════════
  { fn: "CutDirect", category: "Transition", description: "Cuts the input directly to Output without changing Preview", params: ["input"] },
  { fn: "FadeToBlack", category: "Transition", description: "Toggle FTB On/Off", params: [] },
  { fn: "QuickPlay", category: "Transition", description: "", params: ["input"] },
  { fn: "SetFader", category: "Transition", description: "Set Master Fader T-Bar, 255 will cut to Preview Value = Fader 0-255", params: ["value"] },
  { fn: "SetStingerGTInput{slot}", category: "Transition", description: "Assign GT Input as animation source for Stinger 1", params: ["input"], family: [{ id: "slot", kind: "int", min: 1, max: 4, label: "Stinger #" }] },
  { fn: "SetTransitionDuration{slot}", category: "Transition", description: "Change Transition Duration for Button 1 Value = Duration MS", params: ["value"], family: [{ id: "slot", kind: "int", min: 1, max: 4, label: "Button #" }] },
  { fn: "SetTransitionEffect{slot}", category: "Transition", description: "Change Transition for Button 1 Value = Transition", params: ["value"], family: [{ id: "slot", kind: "int", min: 1, max: 4, label: "Button #" }] },
  { fn: "Stinger{slot}", category: "Transition", description: "", params: ["input", "mix"], family: [{ id: "slot", kind: "int", min: 1, max: 4, label: "Stinger #" }] },
  { fn: "Transition{slot}", category: "Transition", description: "Clicks one of the four Transition buttons in the main vMix window.", params: [], family: [{ id: "slot", kind: "int", min: 1, max: 4, label: "Button #" }] },

  // ══════════════════════════ Output ══════════════════════════
  { fn: "Fullscreen", category: "Output", description: "Toggles Fullscreen On or Off", params: [] },
  { fn: "FullscreenOff", category: "Output", description: "", params: [] },
  { fn: "FullscreenOn", category: "Output", description: "", params: [] },
  { fn: "SetOutput2", category: "Output", description: "Change what is displayed on Output 2. Output,Preview,MultiView,Replay,Mix,Input Value = Output, Preview, MultiView, Replay, Mix, Input", params: ["value", "input", "mix"] },
  { fn: "SetOutput3", category: "Output", description: "Change what is displayed on Output 3. Output,Preview,MultiView,Replay,Mix,Input Value = Output, Preview, MultiView, Replay, Mix, Input", params: ["value", "input", "mix"] },
  { fn: "SetOutput4", category: "Output", description: "Change what is displayed on Output 4. Output,Preview,MultiView,Replay,Mix,Input Value = Output, Preview, MultiView, Replay, Mix, Input", params: ["value", "input", "mix"] },
  { fn: "SetOutputExternal2", category: "Output", description: "Change what is displayed on the External2 output. Output,Preview,MultiView,Replay,Mix,Input Value = Output, Preview, MultiView, Replay, Mix, Input", params: ["value", "input", "mix"] },
  { fn: "SetOutputFullscreen", category: "Output", description: "Change what is displayed on the Fullscreen output. Output,Preview,MultiView,Replay,Mix,Input Value = Output, Preview, MultiView, Replay, Mix, Input", params: ["value", "input", "mix"] },
  { fn: "SetOutputFullscreen2", category: "Output", description: "Change what is displayed on the Fullscreen2 output. Output,Preview,MultiView,Replay,Mix,Input Value = Output, Preview, MultiView, Replay, Mix, Input", params: ["value", "input", "mix"] },
  { fn: "Snapshot", category: "Output", description: "Create a snapshot image of the current Output. Optional Value specifies save Filename, otherwise a save file window will appear. Filename can specify date, for example mysnapshot {0:dd MMM yyyy}.jpg Value = Value", params: ["value"] },
  { fn: "SnapshotInput", category: "Output", description: "Create a snapshot image of the selected Input. Optional Value specifies save Filename, otherwise a save file window will appear. Filename can specify date, for example mysnapshot {0:dd MMM yyyy}.jpg Value = Value", params: ["value", "input"] },
  { fn: "StartExternal", category: "Output", description: "", params: [] },
  { fn: "StartMultiCorder", category: "Output", description: "", params: [] },
  { fn: "StartRecording", category: "Output", description: "", params: [] },
  { fn: "StartSRTOutput", category: "Output", description: "Optional output number starting from 0. Leave blank to control Output 1 only. Value = Output", params: ["value"] },
  { fn: "StartStopExternal", category: "Output", description: "", params: [] },
  { fn: "StartStopMultiCorder", category: "Output", description: "", params: [] },
  { fn: "StartStopRecording", category: "Output", description: "", params: [] },
  { fn: "StartStopSRTOutput", category: "Output", description: "Optional output number starting from 0. Leave blank to control Output 1 only. Value = Output", params: ["value"] },
  { fn: "StartStopStreaming", category: "Output", description: "Optional stream number starting from 0. Leave blank to control all streams. Value = Stream", params: ["value"] },
  { fn: "StartStreaming", category: "Output", description: "Optional stream number starting from 0. Leave blank to control all streams. Value = Stream", params: ["value"] },
  { fn: "StopExternal", category: "Output", description: "", params: [] },
  { fn: "StopMultiCorder", category: "Output", description: "", params: [] },
  { fn: "StopRecording", category: "Output", description: "", params: [] },
  { fn: "StopSRTOutput", category: "Output", description: "Optional output number starting from 0. Leave blank to control Output 1 only. Value = Output", params: ["value"] },
  { fn: "StopStreaming", category: "Output", description: "Optional stream number starting from 0. Leave blank to control all streams. Value = Stream", params: ["value"] },
  { fn: "StreamingSetKey", category: "Output", description: "Set Key on Custom RTMP Stream. Optional stream number starting from 0 at start followed by comma, e.g 0,mystreamkey Value = Stream", params: ["value"] },
  { fn: "StreamingSetPassword", category: "Output", description: "Set Password on Custom RTMP Stream. Optional stream number starting from 0 at start followed by comma, e.g 0,password Value = Stream", params: ["value"] },
  { fn: "StreamingSetURL", category: "Output", description: "Set URL on Custom RTMP Stream. Optional stream number starting from 0 at start followed by comma, e.g 0,rtmp://myurl/ Value = Stream", params: ["value"] },
  { fn: "StreamingSetUsername", category: "Output", description: "Set Username on Custom RTMP Stream. Optional stream number starting from 0 at start followed by comma, e.g 0,username Value = Stream", params: ["value"] },
  { fn: "WriteDurationToRecordingLog", category: "Output", description: "Write current recording duration to log file with optional tag text Value. Value = Tag Text", params: ["value"] },

  // ══════════════════════════ Title ══════════════════════════
  { fn: "AdjustCountdown", category: "Title", description: "Seconds to add or subtract from current Countdown time Value = Seconds", params: ["value", "input"] },
  { fn: "ChangeCountdown", category: "Title", description: "Change countdown time according to Value as hh:mm:ss (00:00:00) Value = Time 00:00:00", params: ["value", "input"] },
  { fn: "NextTitlePreset", category: "Title", description: "", params: ["input"] },
  { fn: "PauseCountdown", category: "Title", description: "Pause or Resume Countdown or if complete, Start from beginning.", params: ["input"] },
  { fn: "PauseRender", category: "Title", description: "Freeze Title Input while making multiple updates", params: ["input"] },
  { fn: "PreviousTitlePreset", category: "Title", description: "", params: ["input"] },
  { fn: "ResumeRender", category: "Title", description: "Resume Title Input rendering after making multiple updates", params: ["input"] },
  { fn: "SelectTitlePreset", category: "Title", description: "Value = Preset Index", params: ["value", "input"] },
  { fn: "SetColor", category: "Title", description: "Change Color in Title using HTML #xxxxxxxx format. SelectedIndex or SelectedName can be used to select object. Value = Color", params: ["value", "input"] },
  { fn: "SetCountdown", category: "Title", description: "Set countdown duration according to Value as hh:mm:ss (00:00:00) Value = Duration 00:00:00", params: ["value", "input"] },
  { fn: "SetImage", category: "Title", description: "Change Image in Title according to Filename or empty to clear. SelectedIndex or SelectedName can be used to select image. Value = Filename", params: ["value", "input"] },
  { fn: "SetImageVisible", category: "Title", description: "Toggle Image Visibility in Title SelectedIndex or SelectedName can be used to select image.", params: ["input"] },
  { fn: "SetImageVisibleOff", category: "Title", description: "Hide Image in Title SelectedIndex or SelectedName can be used to select image.", params: ["input"] },
  { fn: "SetImageVisibleOn", category: "Title", description: "Show Image in Title SelectedIndex or SelectedName can be used to select image.", params: ["input"] },
  { fn: "SetText", category: "Title", description: "Change Text in Title according to Value parameter. SelectedIndex or SelectedName can be used to select Text Field Value = Text", params: ["value", "input"] },
  { fn: "SetTextColour", category: "Title", description: "Change Colour of Text in Title in HTML format (#xxxxxx) Value = Colour", params: ["value", "input"] },
  { fn: "SetTextVisible", category: "Title", description: "Toggle Text Visibility in Title SelectedIndex or SelectedName can be used to select text field.", params: ["input"] },
  { fn: "SetTextVisibleOff", category: "Title", description: "Hide Text in Title SelectedIndex or SelectedName can be used to select text field.", params: ["input"] },
  { fn: "SetTextVisibleOn", category: "Title", description: "Show Text in Title SelectedIndex or SelectedName can be used to select text field.", params: ["input"] },
  { fn: "SetTickerSpeed", category: "Title", description: "Change Ticker Speed. SelectedIndex or SelectedName can be used to select ticker field. Value = Speed 0-1000", params: ["value", "input"] },
  { fn: "StartCountdown", category: "Title", description: "", params: ["input"] },
  { fn: "StopCountdown", category: "Title", description: "Stop and Reset Countdown", params: ["input"] },
  { fn: "SuspendCountdown", category: "Title", description: "Pause Countdown Only", params: ["input"] },
  { fn: "TitleBeginAnimation", category: "Title", description: "Value = Animation", params: ["value", "input"] },

  // ══════════════════════════ Input ══════════════════════════
  { fn: "ActiveInput", category: "Input", description: "Send to Output the selected Input", params: ["input", "mix"] },
  { fn: "AddInput", category: "Input", description: "Create a new Input based on information provided in Value. Video|c:\\path\\to\\video.avi Image|c:\\path\\to\\image.jpg Photos|c:\\path\\to\\folder Title|c:\\path\\to\\title.gtzip VideoList|c:\\path\\to\\playlist.m3u Colour|HTMLColor AudioFile|c:\\path\\to\\audio.wav Flash|c:\\path\\to\\flash.swf PowerPoint|c:\\path\\to\\powerpoint.pptx Value = Type|Filename", params: ["value"] },
  { fn: "AutoPauseOff", category: "Input", description: "", params: ["input"] },
  { fn: "AutoPauseOn", category: "Input", description: "", params: ["input"] },
  { fn: "AutoPlayFirst", category: "Input", description: "Toggle automatically playing first item in a List with Transition", params: ["input"] },
  { fn: "AutoPlayFirstOff", category: "Input", description: "Turn Off automatically playing first item in a List with Transition", params: ["input"] },
  { fn: "AutoPlayFirstOn", category: "Input", description: "Turn On automatically playing first item in a List with Transition", params: ["input"] },
  { fn: "AutoPlayNext", category: "Input", description: "Toggle automatically playing next item in a List", params: ["input"] },
  { fn: "AutoPlayNextOff", category: "Input", description: "Turn Off automatically playing next item in a List", params: ["input"] },
  { fn: "AutoPlayNextOn", category: "Input", description: "Turn On automatically playing next item in a List", params: ["input"] },
  { fn: "AutoPlayOff", category: "Input", description: "", params: ["input"] },
  { fn: "AutoPlayOn", category: "Input", description: "", params: ["input"] },
  { fn: "AutoRestartOff", category: "Input", description: "", params: ["input"] },
  { fn: "AutoRestartOn", category: "Input", description: "", params: ["input"] },
  { fn: "ColourCorrectionAuto", category: "Input", description: "Basic Auto Colour Correction.", params: ["input"] },
  { fn: "ColourCorrectionReset", category: "Input", description: "Reset Colour Correction to Default Values.", params: ["input"] },
  { fn: "CreateVirtualInput", category: "Input", description: "Create a new Virtual Input from the specified Input.", params: ["input"] },
  { fn: "DeinterlaceOff", category: "Input", description: "", params: ["input"] },
  { fn: "DeinterlaceOn", category: "Input", description: "", params: ["input"] },
  { fn: "Effect{n}", category: "Input", description: "Toggle Effect 1 On/Off", params: ["input"], family: [{ id: "n", kind: "int", min: 1, max: 4, label: "Effect #" }] },
  { fn: "Effect{n}Off", category: "Input", description: "Turn Effect 1 Off", params: ["input"], family: [{ id: "n", kind: "int", min: 1, max: 4, label: "Effect #" }] },
  { fn: "Effect{n}On", category: "Input", description: "Turn Effect 1 On", params: ["input"], family: [{ id: "n", kind: "int", min: 1, max: 4, label: "Effect #" }] },
  { fn: "InputPreviewHide", category: "Input", description: "Hides large preview of input", params: ["input"] },
  { fn: "InputPreviewShow", category: "Input", description: "Shows large preview of input", params: ["input"] },
  { fn: "InputPreviewShowHide", category: "Input", description: "Toggles large preview of input", params: ["input"] },
  { fn: "LayerOff", category: "Input", description: "Turn Off Layer For Input At Index (starting from 1) Value = Index", params: ["value", "input"] },
  { fn: "LayerOn", category: "Input", description: "Turn On Layer For Input At Index (starting from 1) Value = Index", params: ["value", "input"] },
  { fn: "LayerOnOff", category: "Input", description: "Toggle On/Off Layer For Input At Index (starting from 1) Value = Index", params: ["value", "input"] },
  { fn: "ListAdd", category: "Input", description: "Add Filename to List Value = Filename", params: ["value", "input"] },
  { fn: "ListExport", category: "Input", description: "Export List as M3U to Filename Value = Filename", params: ["value", "input"] },
  { fn: "ListPlayOut", category: "Input", description: "", params: ["input"] },
  { fn: "ListRemove", category: "Input", description: "Remove from List by Index starting from 1 Value = Index", params: ["value", "input"] },
  { fn: "ListRemoveAll", category: "Input", description: "Remove all items from List", params: ["input"] },
  { fn: "ListShowHide", category: "Input", description: "", params: ["input"] },
  { fn: "ListShuffle", category: "Input", description: "Shuffle (randomize) List", params: ["input"] },
  { fn: "LivePlayPause", category: "Input", description: "", params: ["input"] },
  { fn: "Loop", category: "Input", description: "Toggle Loop on Input", params: ["input"] },
  { fn: "LoopOff", category: "Input", description: "", params: ["input"] },
  { fn: "LoopOn", category: "Input", description: "", params: ["input"] },
  { fn: "MarkIn", category: "Input", description: "", params: ["input"] },
  { fn: "MarkOut", category: "Input", description: "", params: ["input"] },
  { fn: "MarkReset", category: "Input", description: "", params: ["input"] },
  { fn: "MarkResetIn", category: "Input", description: "", params: ["input"] },
  { fn: "MarkResetOut", category: "Input", description: "", params: ["input"] },
  { fn: "MirrorOff", category: "Input", description: "", params: ["input"] },
  { fn: "MirrorOn", category: "Input", description: "", params: ["input"] },
  { fn: "MoveInput", category: "Input", description: "Value = Number", params: ["value", "input"] },
  { fn: "MoveLayer", category: "Input", description: "Move Layer in Input according to Value parameter. Example: 1,2 moves Layer1 to Layer2 Value = FromIndex,ToIndex", params: ["value", "input"] },
  { fn: "NextItem", category: "Input", description: "Move to next item in List", params: ["input"] },
  { fn: "NextPicture", category: "Input", description: "Move to Next Picture for Photo and PowerPoint Inputs", params: ["input"] },
  { fn: "Pause", category: "Input", description: "", params: ["input"] },
  { fn: "Play", category: "Input", description: "", params: ["input"] },
  { fn: "PlayPause", category: "Input", description: "", params: ["input"] },
  { fn: "PreviewInput", category: "Input", description: "Send to Preview the selected Input", params: ["input", "mix"] },
  { fn: "PreviewInputNext", category: "Input", description: "Send to Preview the next Input", params: [] },
  { fn: "PreviewInputPrevious", category: "Input", description: "Send to Preview the previous Input", params: [] },
  { fn: "PreviousItem", category: "Input", description: "Move to previous item in List", params: ["input"] },
  { fn: "PreviousPicture", category: "Input", description: "Move to Previous Picture for Photo and PowerPoint Inputs", params: ["input"] },
  { fn: "RemoveInput", category: "Input", description: "", params: ["input"] },
  { fn: "ResetInput", category: "Input", description: "", params: ["input"] },
  { fn: "Restart", category: "Input", description: "Restart selected Input", params: ["input"] },
  { fn: "SaveVideoDelay", category: "Input", description: "Save video clip from Video Delay according to Duration in milliseconds", params: ["input", "duration"] },
  { fn: "SelectCategory", category: "Input", description: "Change to Category according to Value (All,Red,Green,Orange,Purple,Aqua,Blue,Custom1-16,Search) Value = Category", params: ["value"] },
  { fn: "SelectIndex", category: "Input", description: "Photos,List: Selects item in List according to Value starting from number 1 Virtual Set: Zooms to selected preset using the current speed settings Title: Starts Page animation according to Value starting from number 1 Value = Index", params: ["value", "input"] },
  { fn: "SetAlpha", category: "Input", description: "Set Input transparency according to Value. 0 is transparent, 255 is opaque Value = Alpha 0-255", params: ["value", "input"] },
  { fn: "SetCCGainB", category: "Input", description: "Change Gain B level of Input. 1=Original Value = Value 0-2", params: ["value", "input"] },
  { fn: "SetCCGainG", category: "Input", description: "Change Gain G level of Input. 1=Original Value = Value 0-2", params: ["value", "input"] },
  { fn: "SetCCGainR", category: "Input", description: "Change Gain R level of Input. 1=Original Value = Value 0-2", params: ["value", "input"] },
  { fn: "SetCCGainRGB", category: "Input", description: "Change Gain RGB level of Input. 1=Original Value = Value 0-2", params: ["value", "input"] },
  { fn: "SetCCGainY", category: "Input", description: "Change Gain Y level of Input. 1=Original Value = Value 0-2", params: ["value", "input"] },
  { fn: "SetCCGammaB", category: "Input", description: "Change Gamma B level of Input. 0=Original Value = Value -1-1", params: ["value", "input"] },
  { fn: "SetCCGammaG", category: "Input", description: "Change Gamma G level of Input. 0=Original Value = Value -1-1", params: ["value", "input"] },
  { fn: "SetCCGammaR", category: "Input", description: "Change Gamma R level of Input. 0=Original Value = Value -1-1", params: ["value", "input"] },
  { fn: "SetCCGammaRGB", category: "Input", description: "Change Gamma RGB level of Input. 0=Original Value = Value -1-1", params: ["value", "input"] },
  { fn: "SetCCGammaY", category: "Input", description: "Change Gamma Y level of Input. 0=Original Value = Value -1-1", params: ["value", "input"] },
  { fn: "SetCCHue", category: "Input", description: "Change Hue level of Input. 0=Original Value = Value -1-1", params: ["value", "input"] },
  { fn: "SetCCLiftB", category: "Input", description: "Change Lift B level of Input. 0=Original Value = Value -1-1", params: ["value", "input"] },
  { fn: "SetCCLiftG", category: "Input", description: "Change Lift G level of Input. 0=Original Value = Value -1-1", params: ["value", "input"] },
  { fn: "SetCCLiftR", category: "Input", description: "Change Lift R level of Input. 0=Original Value = Value -1-1", params: ["value", "input"] },
  { fn: "SetCCLiftRGB", category: "Input", description: "Change Lift RGB level of Input. 0=Original Value = Value -1-1", params: ["value", "input"] },
  { fn: "SetCCLiftY", category: "Input", description: "Change Lift Y level of Input. 0=Original Value = Value -1-1", params: ["value", "input"] },
  { fn: "SetCCSaturation", category: "Input", description: "Change Saturation level of Input. 0=Original, -1=Greyscale Value = Value -1-1", params: ["value", "input"] },
  { fn: "SetCrop", category: "Input", description: "Change current Crop value of Input. X1,Y1,X2,Y2 (values between 0 and 1) Value = X1,Y1,X2,Y2", params: ["value", "input"] },
  { fn: "SetCropX1", category: "Input", description: "Change current Crop X1 value of Input. 0=No Crop, 1=Full Crop Value = X1 0-1", params: ["value", "input"] },
  { fn: "SetCropX2", category: "Input", description: "Change current Crop X2 value of Input. 1=No Crop, 0=Full Crop Value = X2 0-1", params: ["value", "input"] },
  { fn: "SetCropY1", category: "Input", description: "Change current Crop Y1 value of Input. 0=No Crop, 1=Full Crop Value = Y1 0-1", params: ["value", "input"] },
  { fn: "SetCropY2", category: "Input", description: "Change current Crop Y2 value of Input. 1=No Crop, 0=Full Crop Value = Y2 0-1", params: ["value", "input"] },
  { fn: "SetDynamicInput{n}", category: "Input", description: "Set Dynamic Input from Input Name or Number Value = Input", params: ["value"], family: [{ id: "n", kind: "int", min: 1, max: 4, label: "Slot #" }] },
  { fn: "SetEffect{n}Strength", category: "Input", description: "Set Input 1 Effect Strength Value = Value 0-1", params: ["value", "input"], family: [{ id: "n", kind: "int", min: 1, max: 4, label: "Effect #" }] },
  { fn: "SetFrameDelay", category: "Input", description: "Set the delay in frames Value = Frames", params: ["value", "input"] },
  { fn: "SetInputName", category: "Input", description: "Set the Display Name of the Input Value = Name", params: ["value", "input"] },
  { fn: "SetLayer", category: "Input", description: "Change Layer in Input according to Value parameter. Example: 1,2 changes Layer1 to Input2 Value = Index,Input", params: ["value", "input"] },
  { fn: "SetLayer{n}Crop", category: "Input", description: "Change current Crop value of Input Layer. X1,Y1,X2,Y2 (values between 0 and 1) Value = X1,Y1,X2,Y2", params: ["value", "input"], family: [{ id: "n", kind: "int", min: 1, max: 10, label: "Layer #" }] },
  { fn: "SetLayer{n}CropX1", category: "Input", description: "Change current Crop X1 value of Input Layer. 0=No Crop, 1=Full Crop Value = X1 0-1", params: ["value", "input"], family: [{ id: "n", kind: "int", min: 1, max: 10, label: "Layer #" }] },
  { fn: "SetLayer{n}CropX2", category: "Input", description: "Change current Crop X2 value of Input Layer. 1=No Crop, 0=Full Crop Value = X2 0-1", params: ["value", "input"], family: [{ id: "n", kind: "int", min: 1, max: 10, label: "Layer #" }] },
  { fn: "SetLayer{n}CropY1", category: "Input", description: "Change current Crop Y1 value of Input Layer. 0=No Crop, 1=Full Crop Value = Y1 0-1", params: ["value", "input"], family: [{ id: "n", kind: "int", min: 1, max: 10, label: "Layer #" }] },
  { fn: "SetLayer{n}CropY2", category: "Input", description: "Change current Crop Y2 value of Input Layer. 1=No Crop, 0=Full Crop Value = Y2 0-1", params: ["value", "input"], family: [{ id: "n", kind: "int", min: 1, max: 10, label: "Layer #" }] },
  { fn: "SetLayer{n}Height", category: "Input", description: "Change current Height value of Input Layer. In pixels based on preset resolution Value = Pixels -4096-4096", params: ["value", "input"], family: [{ id: "n", kind: "int", min: 1, max: 10, label: "Layer #" }] },
  { fn: "SetLayer{n}PanX", category: "Input", description: "Change current PanX value of Input Layer. 0=centered, -2=100% to left, 2=100% to right Value = Pan -2-2", params: ["value", "input"], family: [{ id: "n", kind: "int", min: 1, max: 10, label: "Layer #" }] },
  { fn: "SetLayer{n}PanY", category: "Input", description: "Change current PanY value of Input Layer. 0=centered, -2=100% to bottom, 2=100% to top Value = Pan -2-2", params: ["value", "input"], family: [{ id: "n", kind: "int", min: 1, max: 10, label: "Layer #" }] },
  { fn: "SetLayer{n}Rectangle", category: "Input", description: "Change current Rectangle values of Input Layer in pixels. X,Y,Width,Height Value = X,Y,Width,Height", params: ["value", "input"], family: [{ id: "n", kind: "int", min: 1, max: 10, label: "Layer #" }] },
  { fn: "SetLayer{n}Width", category: "Input", description: "Change current Width value of Input Layer. In pixels based on preset resolution Value = Pixels -4096-4096", params: ["value", "input"], family: [{ id: "n", kind: "int", min: 1, max: 10, label: "Layer #" }] },
  { fn: "SetLayer{n}X", category: "Input", description: "Change current X value of Input Layer. In pixels based on preset resolution Value = Pixels -4096-4096", params: ["value", "input"], family: [{ id: "n", kind: "int", min: 1, max: 10, label: "Layer #" }] },
  { fn: "SetLayer{n}Y", category: "Input", description: "Change current Y value of Input Layer. In pixels based on preset resolution Value = Pixels -4096-4096", params: ["value", "input"], family: [{ id: "n", kind: "int", min: 1, max: 10, label: "Layer #" }] },
  { fn: "SetLayer{n}Zoom", category: "Input", description: "Change current Zoom level of Input Layer. 1=100%, 0.5=50%, 2=200% Value = Zoom 0-5", params: ["value", "input"], family: [{ id: "n", kind: "int", min: 1, max: 10, label: "Layer #" }] },
  { fn: "SetLayerAnimated", category: "Input", description: "Change Layer Index to Input. Animate if input exists in another layer. Example: 1,2,1000 changes Layer1 to Input2. Value = Index,Input,DurationMilliseconds", params: ["value", "input"] },
  { fn: "SetLayerDynamicCrop", category: "Input", description: "Change current Crop value of Input Layer from DynamicValue1 (1-10). X1,Y1,X2,Y2 (values between 0 and 1) Value = X1,Y1,X2,Y2", params: ["value", "input"] },
  { fn: "SetLayerDynamicCropX1", category: "Input", description: "Change current Crop X1 value of Input Layer from DynamicValue1 (1-10). 0=No Crop, 1=Full Crop Value = X1 0-1", params: ["value", "input"] },
  { fn: "SetLayerDynamicCropX2", category: "Input", description: "Change current Crop X2 value of Input Layer from DynamicValue1 (1-10). 1=No Crop, 0=Full Crop Value = X2 0-1", params: ["value", "input"] },
  { fn: "SetLayerDynamicCropY1", category: "Input", description: "Change current Crop Y1 value of Input Layer from DynamicValue1 (1-10). 0=No Crop, 1=Full Crop Value = Y1 0-1", params: ["value", "input"] },
  { fn: "SetLayerDynamicCropY2", category: "Input", description: "Change current Crop Y2 value of Input Layer from DynamicValue1 (1-10). 1=No Crop, 0=Full Crop Value = Y2 0-1", params: ["value", "input"] },
  { fn: "SetLayerDynamicHeight", category: "Input", description: "Change current Height value of Input Layer from DynamicValue1 (1-10). In pixels based on preset resolution Value = Pixels -4096-4096", params: ["value", "input"] },
  { fn: "SetLayerDynamicPanX", category: "Input", description: "Change current PanX value of Input Layer from DynamicValue1 (1-10). 0=centered, -2=100% to left, 2=100% to right Value = Pan -2-2", params: ["value", "input"] },
  { fn: "SetLayerDynamicPanY", category: "Input", description: "Change current PanY value of Input Layer from DynamicValue1 (1-10). 0=centered, -2=100% to bottom, 2=100% to top Value = Pan -2-2", params: ["value", "input"] },
  { fn: "SetLayerDynamicRectangle", category: "Input", description: "Change current Rectangle values of Input Layer from DynamicValue1 (1-10) in pixels. X,Y,Width,Height Value = X,Y,Width,Height", params: ["value", "input"] },
  { fn: "SetLayerDynamicWidth", category: "Input", description: "Change current Width value of Input Layer from DynamicValue1 (1-10). In pixels based on preset resolution Value = Pixels -4096-4096", params: ["value", "input"] },
  { fn: "SetLayerDynamicX", category: "Input", description: "Change current X value of Input Layer from DynamicValue1 (1-10). In pixels based on preset resolution Value = Pixels -4096-4096", params: ["value", "input"] },
  { fn: "SetLayerDynamicY", category: "Input", description: "Change current Y value of Input Layer from DynamicValue1 (1-10). In pixels based on preset resolution Value = Pixels -4096-4096", params: ["value", "input"] },
  { fn: "SetLayerDynamicZoom", category: "Input", description: "Change current Zoom level of Input Layer from DynamicValue1 (1-10). 1=100%, 0.5=50%, 2=200% Value = Zoom 0-5", params: ["value", "input"] },
  { fn: "SetPanX", category: "Input", description: "Change current PanX value of Input. 0=centered, -2=100% to left, 2=100% to right Value = Pan -2-2", params: ["value", "input"] },
  { fn: "SetPanY", category: "Input", description: "Change current PanY value of Input. 0=centered, -2=100% to bottom, 2=100% to top Value = Pan -2-2", params: ["value", "input"] },
  { fn: "SetPictureEffect", category: "Input", description: "Set transition effect for Photos and PowerPoint Inputs (Fade, Zoom, etc) Value = Transition", params: ["value", "input"] },
  { fn: "SetPictureEffectDuration", category: "Input", description: "Set duration of transition effect in Milliseconds Value = Duration MS", params: ["value", "input"] },
  { fn: "SetPictureTransition", category: "Input", description: "Set transition time between Photos and PowerPoint slides in Seconds Value = Seconds", params: ["value", "input"] },
  { fn: "SetPosition", category: "Input", description: "Set Position of selected Input according to Value in Milliseconds Value = Milliseconds", params: ["value", "input"] },
  { fn: "SetRate", category: "Input", description: "Set Playback speed/rate for Videos and Video Delays 0.5=50%,1=100%,2=200% etc Value = Speed 0.1-4", params: ["value", "input"] },
  { fn: "SetRateSlowMotion", category: "Input", description: "Set Slow Motion speed for Instant Replay 0.5=50%,1=100% etc Value = Speed 0-1", params: ["value", "input"] },
  { fn: "SetZoom", category: "Input", description: "Change current Zoom level of Input. 1=100%, 0.5=50%, 2=200% Value = Zoom 0-5", params: ["value", "input"] },
  { fn: "SharpenOff", category: "Input", description: "", params: ["input"] },
  { fn: "SharpenOn", category: "Input", description: "", params: ["input"] },
  { fn: "SwapLayerAnimated", category: "Input", description: "Animate swapping the Layers in Input according to Value parameter. Example: 1,2,1000 swaps Layer1 and Layer2 over 1000 milliseconds. Value = FromIndex,ToIndex,DurationMilliseconds", params: ["value", "input"] },
  { fn: "VideoCallAudioSource", category: "Input", description: "Master,Headphones,BusA,BusB,BusC,BusD,BusE,BusF,BusG Value = Source", params: ["value", "input"] },
  { fn: "VideoCallConnect", category: "Input", description: "Value = Name,Password", params: ["value", "input"] },
  { fn: "VideoCallReconnect", category: "Input", description: "", params: ["input"] },
  { fn: "VideoCallVideoSource", category: "Input", description: "Output1,Output2,Output3,Output4 Value = Source", params: ["value", "input"] },
  { fn: "VideoDelayStartRecording", category: "Input", description: "Start Video Delay Recording", params: ["input", "duration"] },
  { fn: "VideoDelayStartStopRecording", category: "Input", description: "Toggle Video Delay Recording", params: ["input", "duration"] },
  { fn: "VideoDelayStopRecording", category: "Input", description: "Stop Video Delay Recording", params: ["input", "duration"] },
  { fn: "WaitForCompletion", category: "Input", description: "Wait for a Video Input to reach the end of playback.", params: ["input", "duration"] },
  { fn: "ZoomJoinMeeting", category: "Input", description: "Value = MeetingID,Password", params: ["value", "input"] },
  { fn: "ZoomMuteSelf", category: "Input", description: "", params: ["input"] },
  { fn: "ZoomSelectParticipantByName", category: "Input", description: "Value = Name", params: ["value", "input"] },
  { fn: "ZoomUnMuteSelf", category: "Input", description: "", params: ["input"] },

  // ══════════════════════════ Overlay ══════════════════════════
  { fn: "MoveMultiViewOverlay", category: "Overlay", description: "Move Overlay in Input MultiView according to Value parameter. Example: 1,2 moves Overlay1 to Overlay2 Value = FromIndex,ToIndex", params: ["value", "input"] },
  { fn: "MultiViewOverlay", category: "Overlay", description: "Toggle On/Off MultiView Overlay For Input At Index (starting from 1) Value = Index", params: ["value", "input"] },
  { fn: "MultiViewOverlayOff", category: "Overlay", description: "Turn Off MultiView Overlay For Input At Index (starting from 1) Value = Index", params: ["value", "input"] },
  { fn: "MultiViewOverlayOn", category: "Overlay", description: "Turn On MultiView Overlay For Input At Index (starting from 1) Value = Index", params: ["value", "input"] },
  { fn: "OverlayInput{ch}", category: "Overlay", description: "Toggle Overlay1 On/Off with selected Input using configured Transition", params: ["input", "mix"], family: [{ id: "ch", kind: "int", min: 1, max: 4, label: "Overlay #" }] },
  { fn: "OverlayInput{ch}In", category: "Overlay", description: "Transition Out to Overlay1 with selected Input", params: ["input", "mix"], family: [{ id: "ch", kind: "int", min: 1, max: 4, label: "Overlay #" }] },
  { fn: "OverlayInput{ch}Last", category: "Overlay", description: "Toggle Overlay1 On/Off with last used Input on this channel", params: ["mix"], family: [{ id: "ch", kind: "int", min: 1, max: 4, label: "Overlay #" }] },
  { fn: "OverlayInput{ch}Off", category: "Overlay", description: "Immediately switch Overlay1 Off (Cut)", params: [], family: [{ id: "ch", kind: "int", min: 1, max: 4, label: "Overlay #" }] },
  { fn: "OverlayInput{ch}Out", category: "Overlay", description: "Transition Out Overlay1", params: [], family: [{ id: "ch", kind: "int", min: 1, max: 4, label: "Overlay #" }] },
  { fn: "OverlayInput{ch}Zoom", category: "Overlay", description: "Zooms PIP Overlay to fill Fullscreen and vice versa", params: [], family: [{ id: "ch", kind: "int", min: 1, max: 4, label: "Overlay #" }] },
  { fn: "OverlayInputAllOff", category: "Overlay", description: "Immediately switch all Overlays Off", params: [] },
  { fn: "PreviewOverlayInput{ch}", category: "Overlay", description: "Preview Overlay1 using the selected Input", params: ["input"], family: [{ id: "ch", kind: "int", min: 1, max: 4, label: "Overlay #" }] },
  { fn: "SetMultiViewOverlay", category: "Overlay", description: "Change Layer in Input MultiView according to Value parameter. Example: 1,2 changes Layer 1 to Input2 Value = Index,Input", params: ["value", "input"] },

  // ══════════════════════════ PlayList ══════════════════════════
  { fn: "NextPlayListEntry", category: "PlayList", description: "Move to Next Item in a running PlayList", params: [] },
  { fn: "PreviousPlayListEntry", category: "PlayList", description: "Move to Previous Item in a running PlayList", params: [] },
  { fn: "SelectPlayList", category: "PlayList", description: "Open PlayList with Name matching Value Value = PlayList", params: ["value"] },
  { fn: "StartPlayList", category: "PlayList", description: "", params: [] },
  { fn: "StopPlayList", category: "PlayList", description: "", params: [] },

  // ══════════════════════════ Scripting ══════════════════════════
  { fn: "ScriptStart", category: "Scripting", description: "Value = Script Name", params: ["value"] },
  { fn: "ScriptStartDynamic", category: "Scripting", description: "Start a dynamic script using code specified as the Value. Value = Code", params: ["value"] },
  { fn: "ScriptStop", category: "Scripting", description: "Value = Script Name", params: ["value"] },
  { fn: "ScriptStopAll", category: "Scripting", description: "", params: [] },
  { fn: "ScriptStopDynamic", category: "Scripting", description: "", params: [] },

  // ══════════════════════════ Replay ══════════════════════════
  { fn: "Replay{chn}Camera{cam}", category: "Replay", description: "", params: [], family: [{ id: "chn", kind: "enum", values: ["A", "B"], label: "Channel" }, { id: "cam", kind: "int", min: 1, max: 8, label: "Camera #" }] },
  { fn: "ReplayCamera{cam}", category: "Replay", description: "", params: [], family: [{ id: "cam", kind: "int", min: 1, max: 8, label: "Camera #" }] },
  { fn: "ReplayChangeDirection", category: "Replay", description: "", params: ["channel"] },
  { fn: "ReplayChangeSpeed", category: "Replay", description: "Value = Speed", params: ["value", "channel"] },
  { fn: "ReplayCopyLastEvent", category: "Replay", description: "Value = Event List 0-19", params: ["value"] },
  { fn: "ReplayCopySelectedEvent", category: "Replay", description: "Value = Event List 0-19", params: ["value"] },
  { fn: "ReplayDeleteLastEvent", category: "Replay", description: "", params: ["channel"] },
  { fn: "ReplayDeleteSelectedEvent", category: "Replay", description: "", params: ["channel"] },
  { fn: "ReplayDuplicateLastEvent", category: "Replay", description: "", params: ["channel"] },
  { fn: "ReplayDuplicateSelectedEvent", category: "Replay", description: "", params: ["channel"] },
  { fn: "ReplayExportLastEvent", category: "Replay", description: "Value = Folder", params: ["value", "channel"] },
  { fn: "ReplayFastBackward", category: "Replay", description: "1-30x Value = Speed", params: ["value", "channel"] },
  { fn: "ReplayFastForward", category: "Replay", description: "1-30x Value = Speed", params: ["value", "channel"] },
  { fn: "ReplayJumpFrames", category: "Replay", description: "Value = Frames", params: ["value", "channel"] },
  { fn: "ReplayJumpFramesFastOff", category: "Replay", description: "ReplayJumpFrames jumps 1 frame for each value instead of 1 second.", params: ["channel"] },
  { fn: "ReplayJumpFramesFastOn", category: "Replay", description: "ReplayJumpFrames jumps 1 second for each value instead of 1 frame.", params: ["channel"] },
  { fn: "ReplayJumpToNow", category: "Replay", description: "", params: ["channel"] },
  { fn: "ReplayJumpToSelectedInPoint", category: "Replay", description: "Set Position to In point of Selected Event.", params: ["channel"] },
  { fn: "ReplayJumpToSelectedOutPoint", category: "Replay", description: "Set Position to Out point of Selected Event.", params: ["channel"] },
  { fn: "ReplayLastEventCameraOff", category: "Replay", description: "Turns off the specified camera angle (1-8) Value = Camera", params: ["value"] },
  { fn: "ReplayLastEventCameraOn", category: "Replay", description: "Turns on the specified camera angle (1-8) Value = Camera", params: ["value"] },
  { fn: "ReplayLastEventSingleCameraOn", category: "Replay", description: "Turns on only the specified camera angle (1-8) Value = Camera", params: ["value"] },
  { fn: "ReplayLive", category: "Replay", description: "", params: [] },
  { fn: "ReplayLiveToggle", category: "Replay", description: "", params: [] },
  { fn: "ReplayMarkCancel", category: "Replay", description: "", params: [] },
  { fn: "ReplayMarkIn", category: "Replay", description: "", params: [] },
  { fn: "ReplayMarkInLive", category: "Replay", description: "", params: [] },
  { fn: "ReplayMarkInOut", category: "Replay", description: "Number of previous seconds to use when creating a new event. Value = Seconds", params: ["value"] },
  { fn: "ReplayMarkInOutLive", category: "Replay", description: "Number of previous seconds to use when creating a new event. Value = Seconds", params: ["value"] },
  { fn: "ReplayMarkInOutLiveFuture", category: "Replay", description: "Number of seconds into the future to use when creating a new event. Value = Seconds", params: ["value"] },
  { fn: "ReplayMarkInOutRecorded", category: "Replay", description: "Number of previous seconds to use when creating a new event. Value = Seconds", params: ["value"] },
  { fn: "ReplayMarkInRecorded", category: "Replay", description: "", params: [] },
  { fn: "ReplayMarkInRecordedNow", category: "Replay", description: "", params: [] },
  { fn: "ReplayMarkOut", category: "Replay", description: "", params: [] },
  { fn: "ReplayMoveLastEvent", category: "Replay", description: "Value = Event List 0-19", params: ["value"] },
  { fn: "ReplayMoveSelectedEvent", category: "Replay", description: "Value = Event List 0-19", params: ["value"] },
  { fn: "ReplayMoveSelectedEventDown", category: "Replay", description: "", params: [] },
  { fn: "ReplayMoveSelectedEventUp", category: "Replay", description: "", params: [] },
  { fn: "ReplayMoveSelectedInPoint", category: "Replay", description: "Value = Frames", params: ["value", "channel"] },
  { fn: "ReplayMoveSelectedOutPoint", category: "Replay", description: "Value = Frames", params: ["value", "channel"] },
  { fn: "ReplayPause", category: "Replay", description: "", params: ["channel"] },
  { fn: "ReplayPlay", category: "Replay", description: "", params: ["channel"] },
  { fn: "ReplayPlayAllEvents", category: "Replay", description: "Play all Events in active list", params: ["channel"] },
  { fn: "ReplayPlayAllEventsToOutput", category: "Replay", description: "Play all Events in active list", params: ["channel"] },
  { fn: "ReplayPlayBackward", category: "Replay", description: "", params: ["channel"] },
  { fn: "ReplayPlayEvent", category: "Replay", description: "Value = Event Number where 0 is bottom of list 0-1000", params: ["value", "channel"] },
  { fn: "ReplayPlayEventsByID", category: "Replay", description: "Value = List of IDs", params: ["value", "channel"] },
  { fn: "ReplayPlayEventsByIDToOutput", category: "Replay", description: "Value = List of IDs", params: ["value", "channel"] },
  { fn: "ReplayPlayEventToOutput", category: "Replay", description: "Value = Event Number where 0 is bottom of list 0-1000", params: ["value", "channel"] },
  { fn: "ReplayPlayForward", category: "Replay", description: "", params: ["channel"] },
  { fn: "ReplayPlayLastEvent", category: "Replay", description: "", params: ["channel"] },
  { fn: "ReplayPlayLastEventToOutput", category: "Replay", description: "", params: ["channel"] },
  { fn: "ReplayPlayNext", category: "Replay", description: "", params: ["channel"] },
  { fn: "ReplayPlayPause", category: "Replay", description: "", params: ["channel"] },
  { fn: "ReplayPlayPrevious", category: "Replay", description: "", params: ["channel"] },
  { fn: "ReplayPlaySelectedEvent", category: "Replay", description: "", params: ["channel"] },
  { fn: "ReplayPlaySelectedEventToOutput", category: "Replay", description: "", params: ["channel"] },
  { fn: "ReplayRecorded", category: "Replay", description: "", params: [] },
  { fn: "ReplayScrollSelectedEvent", category: "Replay", description: "Move back or forward through events list Value = Count -10-10", params: ["value"] },
  { fn: "ReplaySelectAllEvents", category: "Replay", description: "Select all events in active channel.", params: [] },
  { fn: "ReplaySelectChannelA", category: "Replay", description: "", params: [] },
  { fn: "ReplaySelectChannelAB", category: "Replay", description: "", params: [] },
  { fn: "ReplaySelectChannelB", category: "Replay", description: "", params: [] },
  { fn: "ReplaySelectedEventCameraOff", category: "Replay", description: "Turns off the specified camera angle (1-8) Value = Camera", params: ["value"] },
  { fn: "ReplaySelectedEventCameraOn", category: "Replay", description: "Turns on the specified camera angle (1-8) Value = Camera", params: ["value"] },
  { fn: "ReplaySelectedEventSingleCameraOn", category: "Replay", description: "Turns on only the specified camera angle (1-8) Value = Camera", params: ["value"] },
  { fn: "ReplaySelectEvents{n}", category: "Replay", description: "", params: ["channel"], family: [{ id: "n", kind: "int", min: 1, max: 20, label: "List #" }] },
  { fn: "ReplaySelectFirstEvent", category: "Replay", description: "", params: ["channel"] },
  { fn: "ReplaySelectLastEvent", category: "Replay", description: "", params: ["channel"] },
  { fn: "ReplaySelectNextEvent", category: "Replay", description: "", params: ["channel"] },
  { fn: "ReplaySelectPreviousEvent", category: "Replay", description: "", params: ["channel"] },
  { fn: "ReplaySetAudioSource", category: "Replay", description: "Name as per dropdown box. e.g 'Camera1' Value = AudioSource", params: ["value"] },
  { fn: "ReplaySetChannelAToBTimecode", category: "Replay", description: "Set A Timecode to B Timecode", params: [] },
  { fn: "ReplaySetChannelAToBTimecodeAndCamera", category: "Replay", description: "Set A Timecode and Camera to B", params: [] },
  { fn: "ReplaySetChannelBToATimecode", category: "Replay", description: "Set B Timecode to A Timecode", params: [] },
  { fn: "ReplaySetChannelBToATimecodeAndCamera", category: "Replay", description: "Set B Timecode and Camera to A", params: [] },
  { fn: "ReplaySetDirectionBackward", category: "Replay", description: "", params: ["channel"] },
  { fn: "ReplaySetDirectionForward", category: "Replay", description: "", params: ["channel"] },
  { fn: "ReplaySetLastEventText", category: "Replay", description: "Value = Text", params: ["value"] },
  { fn: "ReplaySetLastEventTextCamera", category: "Replay", description: "Changes the text of the specified angle (1-4), example: 3,angle3text Value = Camera,Text", params: ["value"] },
  { fn: "ReplaySetSelectedEventText", category: "Replay", description: "Value = Text", params: ["value"] },
  { fn: "ReplaySetSelectedEventTextCamera", category: "Replay", description: "Changes the text of the specified angle (1-4), example: 3,angle3text Value = Camera,Text", params: ["value"] },
  { fn: "ReplaySetSpeed", category: "Replay", description: "See SetRateSlowMotion Value = Speed 0-1", params: ["value", "channel"] },
  { fn: "ReplaySetTimecode", category: "Replay", description: "Set position to Timecode in format yyyy-MM-ddTHH:mm:ss.fff Value = Timecode", params: ["value", "channel"] },
  { fn: "ReplayShowHide", category: "Replay", description: "", params: [] },
  { fn: "ReplayStartRecording", category: "Replay", description: "", params: [] },
  { fn: "ReplayStartStopRecording", category: "Replay", description: "", params: [] },
  { fn: "ReplayStopEvents", category: "Replay", description: "", params: ["channel"] },
  { fn: "ReplayStopRecording", category: "Replay", description: "", params: [] },
  { fn: "ReplaySwapChannels", category: "Replay", description: "Swap A to B and vice versa, includes angles and playback status.", params: [] },
  { fn: "ReplayToggleLastEventCamera{cam}", category: "Replay", description: "", params: [], family: [{ id: "cam", kind: "int", min: 1, max: 8, label: "Camera #" }] },
  { fn: "ReplayToggleSelectedEventCamera{cam}", category: "Replay", description: "", params: [], family: [{ id: "cam", kind: "int", min: 1, max: 8, label: "Camera #" }] },
  { fn: "ReplayUpdateSelectedInPoint", category: "Replay", description: "Update In point of Selected Event to current Position.", params: ["channel"] },
  { fn: "ReplayUpdateSelectedOutPoint", category: "Replay", description: "Update Mark Out point of Selected Event to current Position.", params: ["channel"] },
  { fn: "ReplayUpdateSelectedSpeed", category: "Replay", description: "Update Selected Event to use Current Speed.", params: ["channel"] },
  { fn: "ReplayUpdateSelectedSpeedDefault", category: "Replay", description: "Update Selected Event to use Default Speed.", params: ["channel"] },
  { fn: "ReplayUpdateSelectedSpeedFromValue", category: "Replay", description: "See SetRateSlowMotion Value = Speed 0-1", params: ["value", "channel"] },

  // ══════════════════════════ NDI ══════════════════════════
  { fn: "NDICommand", category: "NDI", description: "Send specified command to NDI source Value = Command", params: ["value", "input"] },
  { fn: "NDISelectSourceByIndex", category: "NDI", description: "Value = Index 0-100", params: ["value", "input"] },
  { fn: "NDISelectSourceByName", category: "NDI", description: "Value = Name", params: ["value", "input"] },
  { fn: "NDIStartRecording", category: "NDI", description: "", params: ["input"] },
  { fn: "NDIStopRecording", category: "NDI", description: "", params: ["input"] },

  // ══════════════════════════ PTZ ══════════════════════════
  { fn: "PTZCreateVirtualInput", category: "PTZ", description: "Creates a PTZ Virtual Input with the current Position", params: ["input"] },
  { fn: "PTZFocusAuto", category: "PTZ", description: "", params: ["input"] },
  { fn: "PTZFocusFar", category: "PTZ", description: "Value = Speed 0-1", params: ["value", "input"] },
  { fn: "PTZFocusManual", category: "PTZ", description: "", params: ["input"] },
  { fn: "PTZFocusNear", category: "PTZ", description: "Value = Speed 0-1", params: ["value", "input"] },
  { fn: "PTZFocusStop", category: "PTZ", description: "", params: ["input"] },
  { fn: "PTZHome", category: "PTZ", description: "", params: ["input"] },
  { fn: "PTZMoveDown", category: "PTZ", description: "Value = Speed 0-1", params: ["value", "input"] },
  { fn: "PTZMoveDownLeft", category: "PTZ", description: "Value = Speed 0-1", params: ["value", "input"] },
  { fn: "PTZMoveDownRight", category: "PTZ", description: "Value = Speed 0-1", params: ["value", "input"] },
  { fn: "PTZMoveLeft", category: "PTZ", description: "Value = Speed 0-1", params: ["value", "input"] },
  { fn: "PTZMoveRight", category: "PTZ", description: "Value = Speed 0-1", params: ["value", "input"] },
  { fn: "PTZMoveStop", category: "PTZ", description: "Stop all PTZ movement", params: ["input"] },
  { fn: "PTZMoveToVirtualInputPosition", category: "PTZ", description: "Moves to the Position of the PTZ Virtual Input without selecting it into Preview", params: ["input"] },
  { fn: "PTZMoveToVirtualInputPositionByIndex", category: "PTZ", description: "Moves to the Position of the PTZ Virtual Input associated with this Input. Index is first Input found starting from 0 Value = Index 0-100", params: ["value", "input"] },
  { fn: "PTZMoveUp", category: "PTZ", description: "Value = Speed 0-1", params: ["value", "input"] },
  { fn: "PTZMoveUpLeft", category: "PTZ", description: "Value = Speed 0-1", params: ["value", "input"] },
  { fn: "PTZMoveUpRight", category: "PTZ", description: "Value = Speed 0-1", params: ["value", "input"] },
  { fn: "PTZUpdateVirtualInput", category: "PTZ", description: "Updates selected PTZ Virtual Input with current Position", params: ["input"] },
  { fn: "PTZZoomIn", category: "PTZ", description: "Value = Speed 0-1", params: ["value", "input"] },
  { fn: "PTZZoomOut", category: "PTZ", description: "Value = Speed 0-1", params: ["value", "input"] },
  { fn: "PTZZoomStop", category: "PTZ", description: "", params: ["input"] },

  // ══════════════════════════ Preset ══════════════════════════
  { fn: "LastPreset", category: "Preset", description: "Load the last preset.", params: [] },
  { fn: "OpenPreset", category: "Preset", description: "Load preset from the specified Filename. Value = Filename", params: ["value"] },
  { fn: "SavePreset", category: "Preset", description: "Save preset to the specified Filename. Value = Filename", params: ["value"] },

  // ══════════════════════════ DataSources ══════════════════════════
  { fn: "DataSourceAutoNextOff", category: "DataSources", description: "Name of the Data Source, Table Name (optional) eg 'Excel/CSV,Sheet1' Value = Name,Table", params: ["value"] },
  { fn: "DataSourceAutoNextOn", category: "DataSources", description: "Name of the Data Source, Table Name (optional) eg 'Excel/CSV,Sheet1' Value = Name,Table", params: ["value"] },
  { fn: "DataSourceAutoNextOnOff", category: "DataSources", description: "Name of the Data Source, Table Name (optional) eg 'Excel/CSV,Sheet1' Value = Name,Table", params: ["value"] },
  { fn: "DataSourceNextRow", category: "DataSources", description: "Name of the Data Source and Table Name (optional) eg 'Excel/CSV,Sheet1' Value = Name,Table", params: ["value"] },
  { fn: "DataSourcePause", category: "DataSources", description: "Name of Data Source eg 'Excel/CSV' Value = Name", params: ["value"] },
  { fn: "DataSourcePlay", category: "DataSources", description: "Name of Data Source eg 'Excel/CSV' Value = Name", params: ["value"] },
  { fn: "DataSourcePlayPause", category: "DataSources", description: "Name of Data Source eg 'Excel/CSV' Value = Name", params: ["value"] },
  { fn: "DataSourcePreviousRow", category: "DataSources", description: "Name of the Data Source and Table Name (optional) eg 'Excel/CSV,Sheet1' Value = Name,Table", params: ["value"] },
  { fn: "DataSourceSelectRow", category: "DataSources", description: "Name of the Data Source, Table Name (optional) and Row Index starting from 0 eg 'Excel/CSV,Sheet1,5' Value = Name,Table,Index", params: ["value"] },

  // ══════════════════════════ Browser ══════════════════════════
  { fn: "BrowserBack", category: "Browser", description: "", params: ["input"] },
  { fn: "BrowserForward", category: "Browser", description: "", params: ["input"] },
  { fn: "BrowserKeyboardDisabled", category: "Browser", description: "", params: ["input"] },
  { fn: "BrowserKeyboardEnabled", category: "Browser", description: "", params: ["input"] },
  { fn: "BrowserMouseDisabled", category: "Browser", description: "", params: ["input"] },
  { fn: "BrowserMouseEnabled", category: "Browser", description: "", params: ["input"] },
  { fn: "BrowserNavigate", category: "Browser", description: "URL Value = URL", params: ["value", "input"] },
  { fn: "BrowserReload", category: "Browser", description: "", params: ["input"] },
];

/**
 * Resolve a (possibly templated) shortcut into a concrete vMix Function
 * name by substituting the chosen family values.
 *   buildVmixFunction("OverlayInput{ch}", { ch: 2 }) === "OverlayInput2"
 */
export function buildVmixFunction(
  fn: string,
  selection: Record<string, string | number> = {},
): string {
  return fn.replace(/\{(\w+)\}/g, (_, id) => {
    const v = selection[id];
    if (v === undefined) {
      throw new Error(`buildVmixFunction: missing family value "${id}" for "${fn}"`);
    }
    return String(v);
  });
}

/** Total documented functions represented (expanded count). */
export const VMIX_SHORTCUT_COUNT = 713;
