import { NextRequest, NextResponse } from "next/server";

export const dynamic = "force-dynamic";

export async function GET(request: NextRequest) {
  // Use the Host header (the actual address the browser hit) rather than
  // request.nextUrl.origin — when the server is bound to 0.0.0.0 (Electron
  // launcher default), nextUrl.origin returns http://0.0.0.0:PORT, which the
  // downloaded .bat can never reach.
  const hostHeader = request.headers.get("host");
  const forwardedProto = request.headers.get("x-forwarded-proto");
  // Whitelist proto + host before they're interpolated into the generated
  // PowerShell. A poisoned Host header could otherwise break out of the
  // double-quoted PS strings the origin lands in (`Invoke-RestMethod -Uri
  // "<origin>/..."`) and inject commands into the .bat the operator runs.
  const proto =
    forwardedProto === "https"
      ? "https"
      : forwardedProto === "http"
        ? "http"
        : request.nextUrl.protocol.replace(":", "");
  // host[:port] — letters/digits/dot/hyphen for the host, optional :port.
  const HOST_RE = /^[A-Za-z0-9.-]+(:\d{1,5})?$/;
  const host =
    hostHeader && HOST_RE.test(hostHeader) ? hostHeader : request.nextUrl.host;
  const origin = `${proto}://${host}`;
  const ps1 = buildPs1(origin);

  // Encode PS1 as UTF-16LE base64 for PowerShell -EncodedCommand
  const buf = Buffer.alloc(ps1.length * 2);
  for (let i = 0; i < ps1.length; i++) {
    buf.writeUInt16LE(ps1.charCodeAt(i), i * 2);
  }
  const encoded = buf.toString("base64");

  const bat = [
    "@echo off",
    "title Network Scanner",
    `powershell -NoProfile -ExecutionPolicy Bypass -EncodedCommand ${encoded}`,
    "pause",
  ].join("\r\n");

  return new NextResponse(bat, {
    headers: {
      "Content-Type": "application/octet-stream",
      "Content-Disposition": 'attachment; filename="network-scanner.bat"',
    },
  });
}

function buildPs1(origin: string): string {
  const resultsApi = `${origin}/api/network/results`;
  const callbackUrl = `${origin}/network`;

  return [
    "$ErrorActionPreference = 'SilentlyContinue'",
    "$host.UI.RawUI.WindowTitle = 'Network Scanner'",
    "",
    'Write-Host ""',
    'Write-Host "  Network Scanner" -ForegroundColor Cyan',
    'Write-Host "  ---------------" -ForegroundColor DarkGray',
    'Write-Host "  Discovers every device on the local subnet" -ForegroundColor DarkGray',
    'Write-Host "  (vMix, OBS, grandMA, X32, PCs, cameras...)" -ForegroundColor DarkGray',
    'Write-Host ""',
    "",
    "# ── Detect public IP ──",
    "$publicIP = ''",
    "try {",
    "    $publicIP = (Invoke-RestMethod -Uri 'https://api.ipify.org' -TimeoutSec 5).Trim()",
    '    Write-Host "  Public IP: $publicIP" -ForegroundColor White',
    "} catch {",
    '    Write-Host "  [!] Could not detect public IP" -ForegroundColor Yellow',
    "}",
    'Write-Host ""',
    "",
    "# ── MAC vendor lookup ──",
    "$oui = @{",
    '    "00:50:56"="VMware"; "00:0C:29"="VMware"; "00:15:5D"="Hyper-V"',
    '    "B8:27:EB"="Raspberry Pi"; "DC:A6:32"="Raspberry Pi"; "E4:5F:01"="Raspberry Pi"',
    '    "00:1A:79"="Ubiquiti"; "24:5A:4C"="Ubiquiti"; "74:83:C2"="Ubiquiti"; "FC:EC:DA"="Ubiquiti"',
    '    "00:0F:66"="Cisco"; "00:1B:0D"="Cisco"; "F4:CF:E2"="Cisco"',
    '    "04:D9:F5"="Cisco Meraki"; "00:18:0A"="Cisco Meraki"',
    '    "08:55:31"="TP-Link"; "50:C7:BF"="TP-Link"; "98:DA:C4"="TP-Link"',
    '    "28:6F:7F"="Netgear"; "A0:40:A0"="Netgear"; "C0:3F:0E"="Netgear"',
    '    "C8:7F:54"="MikroTik"; "00:0C:42"="MikroTik"; "74:4D:28"="MikroTik"',
    '    "60:38:E0"="Belkin"; "94:10:3E"="Belkin"',
    '    "00:1D:7E"="D-Link"; "1C:BD:B9"="D-Link"',
    '    "00:0E:8F"="Fortinet"; "70:4C:A5"="Fortinet"',
    '    "A8:5C:2C"="Apple"; "3C:22:FB"="Apple"; "F0:18:98"="Apple"; "AC:DE:48"="Apple"',
    '    "00:03:93"="Apple"; "F4:5C:89"="Apple"; "DC:A4:CA"="Apple"; "78:7B:8A"="Apple"',
    '    "A4:83:E7"="Apple"; "14:98:77"="Apple"; "BC:D0:74"="Apple"; "40:A6:D9"="Apple"',
    '    "00:15:99"="Samsung"; "F0:25:B7"="Samsung"; "8C:77:12"="Samsung"',
    '    "00:50:F2"="Microsoft"; "7C:1E:52"="Microsoft"',
    '    "00:1B:21"="Intel"; "3C:97:0E"="Intel"; "A4:C3:F0"="Intel"',
    '    "00:14:22"="Dell"; "F0:4D:A2"="Dell"; "24:B6:FD"="Dell"',
    '    "00:1A:4B"="HP"; "3C:D9:2B"="HP"; "94:57:A5"="HP"',
    '    "00:06:1B"="Lenovo"; "28:D2:44"="Lenovo"; "98:FA:9B"="Lenovo"',
    '    "7C:2E:0D"="Blackmagic"; "00:0D:4B"="Roku"',
    '    "48:D6:D5"="Google"; "F4:F5:D8"="Google"; "54:60:09"="Google"',
    '    "00:04:20"="Audinate"; "00:0A:E4"="Extron"; "00:1C:91"="Crestron"',
    '    "B8:31:B5"="Sonos"; "00:0E:58"="Sonos"; "54:2A:1B"="Sonos"',
    '    "00:17:88"="Philips Hue"; "EC:B5:FA"="Philips Hue"',
    '    "B0:A7:B9"="QNAP"; "00:11:32"="Synology"',
    '    "F0:F0:A4"="Amazon"; "44:65:0D"="Amazon"',
    '    "00:1A:92"="ASUS"; "04:D4:C4"="ASUS"; "2C:FD:A1"="ASUS"',
    "}",
    "",
    "function Get-Vendor($mac) {",
    '    if (-not $mac) { return "" }',
    "    $prefix = ($mac.ToUpper() -replace '-',':').Substring(0,8)",
    "    if ($oui.ContainsKey($prefix)) { return $oui[$prefix] }",
    '    return ""',
    "}",
    "",
    "# ── Detect local subnet ──",
    "$adapters = Get-NetIPAddress -AddressFamily IPv4 |",
    "    Where-Object { $_.IPAddress -ne '127.0.0.1' -and $_.PrefixOrigin -ne 'WellKnown' } |",
    "    Sort-Object -Property InterfaceIndex",
    "",
    "if (-not $adapters) {",
    '    Write-Host "  [!] No active network adapter found." -ForegroundColor Red',
    '    Read-Host "  Press Enter to exit"',
    "    exit 1",
    "}",
    "",
    "$localIP = $adapters[0].IPAddress",
    "$parts = $localIP.Split('.')",
    '$subnet = "$($parts[0]).$($parts[1]).$($parts[2])"',
    "",
    'Write-Host "  Local IP : $localIP" -ForegroundColor White',
    'Write-Host "  Subnet   : $subnet.0/24" -ForegroundColor White',
    'Write-Host ""',
    'Write-Host "  Phase 1/3: Ping sweep..." -ForegroundColor Yellow',
    'Write-Host ""',
    "",
    "# ── Phase 1: Ping sweep ──",
    "$alive = [System.Collections.Concurrent.ConcurrentBag[string]]::new()",
    "$pool = [runspacefactory]::CreateRunspacePool(1, 80)",
    "$pool.Open()",
    "$handles = @()",
    "",
    "foreach ($i in 1..254) {",
    '    $target = "$subnet.$i"',
    "    $ps = [powershell]::Create()",
    "    $ps.RunspacePool = $pool",
    "    [void]$ps.AddScript({",
    "        param($ip, $bag)",
    "        $ping = New-Object System.Net.NetworkInformation.Ping",
    "        try {",
    "            $reply = $ping.Send($ip, 1000)",
    '            if ($reply.Status -eq "Success") { $bag.Add($ip) }',
    "        } catch {}",
    "        $ping.Dispose()",
    "    }).AddArgument($target).AddArgument($alive)",
    "    $handles += @{ PS = $ps; Handle = $ps.BeginInvoke() }",
    "}",
    "",
    "$total = $handles.Count",
    "for ($idx = 0; $idx -lt $total; $idx++) {",
    "    $h = $handles[$idx]",
    "    $h.PS.EndInvoke($h.Handle)",
    "    $h.PS.Dispose()",
    "    if (($idx + 1) % 20 -eq 0 -or $idx -eq $total - 1) {",
    '        $pct = [math]::Round((($idx + 1) / $total) * 100)',
    '        Write-Host "`r  Ping: $pct% ($($idx+1)/254)  " -NoNewline -ForegroundColor DarkGray',
    "    }",
    "}",
    "$pool.Close()",
    "$pool.Dispose()",
    'Write-Host ""',
    "",
    "$aliveList = @($alive.ToArray() | Sort-Object { [int]($_.Split('.')[-1]) })",
    "",
    "if ($aliveList.Count -eq 0) {",
    '    Write-Host ""',
    '    Write-Host "  [!] No hosts found on $subnet.0/24" -ForegroundColor Red',
    '    Read-Host "  Press Enter to exit"',
    "    exit 0",
    "}",
    "",
    'Write-Host ""',
    'Write-Host "  Found $($aliveList.Count) alive host(s)" -ForegroundColor Green',
    'Write-Host ""',
    "",
    "# ── Phase 2: MAC from ARP ──",
    'Write-Host "  Phase 2/3: Reading MAC addresses..." -ForegroundColor Yellow',
    "$arpTable = @{}",
    "$neighbors = Get-NetNeighbor -AddressFamily IPv4 | Where-Object { $_.State -ne 'Unreachable' }",
    "foreach ($n in $neighbors) {",
    '    if ($n.LinkLayerAddress -and $n.LinkLayerAddress -ne "00-00-00-00-00-00") {',
    "        $arpTable[$n.IPAddress] = $n.LinkLayerAddress",
    "    }",
    "}",
    'Write-Host "  Got $($arpTable.Count) MAC entries" -ForegroundColor DarkGray',
    'Write-Host ""',
    "",
    "# ── Phase 3: Details (parallel) ──",
    'Write-Host "  Phase 3/3: Scanning details (hostname, ports, services)..." -ForegroundColor Yellow',
    'Write-Host ""',
    "",
    "$results = [System.Collections.Concurrent.ConcurrentBag[hashtable]]::new()",
    "$pool2 = [runspacefactory]::CreateRunspacePool(1, 30)",
    "$pool2.Open()",
    "$handles2 = @()",
    "# Ports we probe per host. AV-control ports first (vMix 8088, OBS",
    "# 4455, grandMA OSC 8000/9000, X32 OSC 10023), then generic OS /",
    "# service ports so every machine still gets a useful fingerprint.",
    "$checkPorts = @(22, 80, 443, 445, 548, 554, 3389, 4455, 8000, 8088, 8080, 9000, 9100, 10023, 62078)",
    "",
    "foreach ($ip in $aliveList) {",
    "    $mac = if ($arpTable.ContainsKey($ip)) { $arpTable[$ip] } else { '' }",
    "    $ps = [powershell]::Create()",
    "    $ps.RunspacePool = $pool2",
    "    [void]$ps.AddScript({",
    "        param($targetIP, $macAddr, $ports, $bag)",
    "        $entry = @{",
    "            ip = $targetIP",
    "            mac = $macAddr",
    '            hostname = ""',
    "            openPorts = @()",
    '            vmixVersion = ""',
    '            vmixEdition = ""',
    "            isVmix = $false",
    "            isObs = $false",
    '            obsWebSocketVersion = ""',
    "        }",
    "        try {",
    "            $dns = [System.Net.Dns]::GetHostEntry($targetIP)",
    "            if ($dns.HostName -and $dns.HostName -ne $targetIP) {",
    "                $entry.hostname = $dns.HostName",
    "            }",
    "        } catch {}",
    "        $open = @()",
    "        foreach ($p in $ports) {",
    "            try {",
    "                $c = New-Object System.Net.Sockets.TcpClient",
    "                $ar = $c.BeginConnect($targetIP, $p, $null, $null)",
    "                if ($ar.AsyncWaitHandle.WaitOne(800, $false) -and $c.Connected) {",
    "                    $open += $p",
    "                }",
    "                $c.Close()",
    "            } catch {}",
    "        }",
    "        $entry.openPorts = $open",
    "        if ($open -contains 8088) {",
    "            try {",
    "                $wc = New-Object System.Net.WebClient",
    '                $xml = [xml]$wc.DownloadString("http://$($targetIP):8088/api")',
    "                $entry.vmixVersion = $xml.vmix.version",
    "                $entry.vmixEdition = $xml.vmix.edition",
    "                if ($entry.vmixVersion) { $entry.isVmix = $true }",
    "            } catch {}",
    "        }",
    "        if ($open -contains 4455) {",
    "            # obs-websocket v5 handshake: open a WS, read the Hello",
    "            # frame, pull the version from its payload. Two-second",
    "            # cap per host keeps the scan snappy when 4455 happens",
    "            # to be open on a non-OBS service.",
    "            try {",
    "                $ws = New-Object System.Net.WebSockets.ClientWebSocket",
    "                $ws.Options.AddSubProtocol('obswebsocket.json')",
    "                $cts = New-Object System.Threading.CancellationTokenSource",
    "                $cts.CancelAfter([TimeSpan]::FromSeconds(2))",
    `                $connect = $ws.ConnectAsync([Uri]"ws://$($targetIP):4455", $cts.Token)`,
    "                $connect.Wait()",
    "                if ($ws.State -eq 'Open') {",
    "                    $buf = New-Object byte[] 4096",
    "                    $seg = New-Object System.ArraySegment[byte] -ArgumentList @(,$buf)",
    "                    $recv = $ws.ReceiveAsync($seg, $cts.Token)",
    "                    $recv.Wait()",
    "                    $text = [System.Text.Encoding]::UTF8.GetString($buf, 0, $recv.Result.Count)",
    "                    $obj = $text | ConvertFrom-Json",
    "                    if ($obj.op -eq 0) {",
    "                        $entry.isObs = $true",
    "                        $entry.obsWebSocketVersion = [string]$obj.d.obsWebSocketVersion",
    "                    }",
    "                    try { $ws.Abort() } catch {}",
    "                }",
    "                $ws.Dispose()",
    "            } catch {}",
    "        }",
    "        $bag.Add($entry)",
    "    }).AddArgument($ip).AddArgument($mac).AddArgument($checkPorts).AddArgument($results)",
    "    $handles2 += @{ PS = $ps; Handle = $ps.BeginInvoke() }",
    "}",
    "",
    "$total2 = $handles2.Count",
    "for ($idx = 0; $idx -lt $total2; $idx++) {",
    "    $h = $handles2[$idx]",
    "    $h.PS.EndInvoke($h.Handle)",
    "    $h.PS.Dispose()",
    "    if (($idx + 1) % 3 -eq 0 -or $idx -eq $total2 - 1) {",
    '        $pct = [math]::Round((($idx + 1) / $total2) * 100)',
    '        Write-Host "`r  Details: $pct% ($($idx+1)/$total2)  " -NoNewline -ForegroundColor DarkGray',
    "    }",
    "}",
    "$pool2.Close()",
    "$pool2.Dispose()",
    'Write-Host ""',
    "",
    "$resultList = @($results.ToArray() | Sort-Object { [int]($_.ip.Split('.')[-1]) })",
    "",
    'Write-Host ""',
    "foreach ($r in $resultList) {",
    '    $label = "  $($r.ip)"',
    "    $vendor = Get-Vendor $r.mac",
    '    if ($vendor) { $label += "  [$vendor]" }',
    '    if ($r.hostname) { $label += "  ($($r.hostname))" }',
    "    if ($r.isVmix) {",
    '        $label += "  >> vMix v$($r.vmixVersion) $($r.vmixEdition)"',
    '        Write-Host $label -ForegroundColor Green',
    "    } elseif ($r.isObs) {",
    '        $label += "  >> OBS ws $($r.obsWebSocketVersion)"',
    '        Write-Host $label -ForegroundColor Cyan',
    "    } else {",
    '        Write-Host $label -ForegroundColor White',
    "    }",
    "}",
    "",
    "# ── Send results to app ──",
    'Write-Host ""',
    `Write-Host "  Sending results to: ${resultsApi}" -ForegroundColor Cyan`,
    "",
    "$hostArray = @()",
    "foreach ($r in $resultList) {",
    "    $vendor = Get-Vendor $r.mac",
    "    $hostArray += @{",
    "        ip = $r.ip",
    "        hostname = $r.hostname",
    "        mac = $r.mac",
    "        vendor = $vendor",
    "        openPorts = @($r.openPorts)",
    "        vmixVersion = $r.vmixVersion",
    "        vmixEdition = $r.vmixEdition",
    "        isVmix = $r.isVmix",
    "        isObs = $r.isObs",
    "        obsWebSocketVersion = $r.obsWebSocketVersion",
    "    }",
    "}",
    "",
    "$payload = @{",
    "    hosts = $hostArray",
    "    subnet = $subnet",
    "    publicIP = $publicIP",
    "} | ConvertTo-Json -Depth 5 -Compress",
    "",
    "try {",
    `    $response = Invoke-RestMethod -Uri "${resultsApi}" -Method POST -Body $payload -ContentType "application/json"`,
    "    $scanId = $response.id",
    `    $url = "${callbackUrl}?scan=$scanId"`,
    '    Write-Host "  Opening results in your browser..." -ForegroundColor Cyan',
    "    Start-Process $url",
    "} catch {",
    '    Write-Host "  [!] Failed to send results: $($_.Exception.Message)" -ForegroundColor Red',
    `    Write-Host "  Target URL was: ${resultsApi}" -ForegroundColor DarkGray`,
    '    Write-Host "  Check that the launcher is running at this address." -ForegroundColor Yellow',
    '    Write-Host "  If the URL is wrong, re-download the .bat from the Network page." -ForegroundColor Yellow',
    "}",
    "",
    'Write-Host ""',
    'Write-Host "  Done! You can close this window." -ForegroundColor Green',
    'Write-Host ""',
    "Start-Sleep -Seconds 5",
  ].join("\r\n");
}
